### ISSUE TITLE
App is crashing on startup

### ISSUE THREAD

**Issue by chandanmagic** [DerLobi/XcoatOfPaint#1]
![Screenshot 2021-05-04 at 9 19 09 PM](https://user-images.githubusercontent.com/83293900/117032004-c2937580-ad1e-11eb-98c6-4598990b4d3c.png)
It's crash on HueSlider.draw(_). I have Xcode(12.4).

**Comment by DerLobi** [comment]
@chandanmagic which macOS version are you on?

**Comment by chandanmagic** [comment]
@DerLobi its 10.15.7

**Comment by DerLobi** [comment]
I have to admit I only tested it on Big Sur. I will fix the issue once I have a Catalina VM up and running.
In the meantime you can change the hue slider's class from `HueSlider` to `NSSlider` in the Storyboard.

**Comment by chandanmagic** [comment]
@DerLobi can you delete this issue. By mistake i have used somebody else account. i will raise it with my account.
