### ISSUE TITLE
CoreUI not found

### ISSUE THREAD

**Issue by smashkins** [DerLobi/XcoatOfPaint#3]
I cloned the repo but on xcode 12.5 I have this error:
`error: /Users/username/Documents/System/Library/PrivateFrameworks/CoreUI.framework: No such file or directory (in target 'XcoatOfPaint' from project 'XcoatOfPaint')`

If I download it from zip file coreUI is present

**Comment by DerLobi** [comment]
Thanks for reporting, should be fixed now!
