### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Elliot727** [DerLobi/XcoatOfPaint#5]
I don't know if this is updated anymore but when I try to run the app on my Mac I get this error

Showing All Messages
failed to emit precompiled header '/Users/elliot/Library/Developer/Xcode/DerivedData/XcoatOfPaint-bysvurgiyslgcdcggasppcbymhum/Build/Intermediates.noindex/PrecompiledHeaders/XcoatOfPaint-Bridging-Header-swift_34CLKPR4NZ73W-clang_CNNVHBSYRIHN.pch' for bridging header '/Users/elliot/Downloads/XcoatOfPaint-1.1.2/XcoatOfPaint/XcoatOfPaint-Bridging-Header.h'

**Comment by DerLobi** [comment]
Hey thanks for alerting me to this. I haven't tried building it on Monterey so far.
I'll have a fixed version up in a few minutes.

If you just want to use the app you don't have to build it from source. You can [download the latest version from here](https://github.com/DerLobi/XcoatOfPaint/releases/download/1.2/XcoatOfPaint.zip), it will also run on Monterey.

**Comment by DerLobi** [comment]
Fixed in https://github.com/DerLobi/XcoatOfPaint/releases/tag/1.2.1
