### ISSUE TITLE
Could you add to Readme where icon stored?

### ISSUE THREAD

**Issue by lolgear** [DerLobi/XcoatOfPaint#6]
I noticed that you use method of NSWorkspace, but, it would be nice if this icon can be saved somehow. So, could add a an option to save icon locally via updating Readme or adding "Extract icon" button?

**Comment by DerLobi** [comment]
Good idea! I implemented it and released a new version: https://github.com/DerLobi/XcoatOfPaint/releases/tag/1.3
Just press ⌘ + S 🥳
