### ISSUE TITLE
Make this support other applications

### ISSUE THREAD

**Issue by Nikoloutsos** [DerLobi/XcoatOfPaint#7]
I think it would be even sexier if you can do the same thing to other applications as well

**Comment by DerLobi** [comment]
This repo focuses on Xcode and related applications. The Xcode icon only uses one hue of blue and the rest is monochrome, so shifting that hue is easy.

Feel free to fork the repo and tweak for other Applications. Here's an example of how someone did that: https://github.com/mesopelagique/4DPaintIcon
